### PR TITLE
Fixes post/put calls and adjust promises to accept parameters

### PR DESCRIPTION
**Pull request by binarykitchen**
See https://github.com/basti1302/traverson-angular/issues/2

### CODE REVIEW

**Comment by xogeny** [comment]
I ran into this bug as well.  Since the CI build passed and it can be merged automatically, could you merge this?  Should just take a second with the GitHub API.

**Comment by basti1302** [comment]
Just merging this is not the point. A cursory overview yields that this PR is not clean and can not be merged as is (traverson dep in package.json is wrong, version number of package has been changed (which should not be part of a PR)), versions of other packages have been changed, ...).

Also, what good is a merge of this without a new release? So this will all take some time.

I know this bug renders traverson-angular useless and I know it's overdue to be fixed. I'll get around to this, I promise.

**Comment by xogeny** [comment]
I agree.  I hadn't really paid attention to the `package.json` changes.  But I've applied the changes in `traverson-angular.js` myself and they seem to work fine.

Would it be helpful if I created a separate PR that leaves off the changes to `package.json`? (or perhaps @binarykitchen will beat me to it).

**Comment by basti1302** [comment]
That will not speed it up I'm afraid.

**Comment by xogeny** [comment]
OK.  Just trying to help.

**Comment by basti1302** [comment]
I cherry picked two of the three commits. Thanks for the PR.

**Comment by basti1302** [comment]
this was published with 1.0.0

**Comment by binarykitchen** [comment]
great, thanks!

**Pull request closed without merging**
